name: run-fetch_process-article

on:
  workflow_dispatch:
  schedule:
    - cron: "41 12 * * *" # 6:11 PM IST

jobs:
  embed-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: building (installing deps / transpiling)
        run: cd ./cron && npm run prod 

      - name: Run indexjs Script
        env:
          PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          BACKEND_GRAPHQL_URL: ${{ secrets.BACKEND_GRAPHQL_URL }}
          MODE: ${ secrets.MODE }
          COHERE_API_KEY: ${{ secrets.COHERE_API_KEY }}
        run: node cron/dist/index.js
